[build-system]
requires = ["scikit-build-core", "setuptools", "wheel", "nanobind"]
build-backend = "scikit_build_core.build"

[project]
name = "infinity_sdk"
version = "0.2.0.dev2"
requires-python = ">=3.10"
dependencies = [
    "sqlglot~=11.7.1",
    "pydantic~=2.7.1",
    "thrift~=0.20.0",
    "setuptools~=69.5.1",
    "pytest~=8.2.0",
    "pandas~=2.2.2",
    "numpy~=1.26.4",
    "pyarrow~=16.0.0",
    "polars~=0.20.23",
    "openpyxl~=3.1.2"
]

[tool.scikit-build]
# Protect the configuration against future changes in scikit-build-core
minimum-version = "0.4"

# Setuptools-style build caching in a local directory
build-dir = "build/{wheel_tag}"

#[tool.scikit-build.wheel]
# Build stable ABI wheels for CPython 3.12+
wheel.py-api = "cp312"
#wheel.packages = ["src/embedded_infinity", "python/infinity", "python/infinity/remote_thrift", "python/infinity/remote_thrift/infinity_thrift_rpc"]
wheel.packages = ["src/embedded_infinity", "python/infinity"]

[tool.cibuildwheel]
# Necessary to see build output from the actual compilation
build-verbosity = 1

# Run pytest to ensure that the package was correctly built
#test-command = "pytest {project}/tests"
#test-requires = "pytest"

# Needed for full C++17 support
[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "10.14"